### ISSUE TITLE
Nexus Repo?

### ISSUE THREAD

**Issue by ThunderGemios10** [OgarProject/Ogar2-API#1]
Is there a Ogar2-API nexus repo ?

I am creating a sample plugin working with Maven.
However i am unable to fetch the dependencies without a repo.

**Comment by avafloww** [comment]
Not currently, as it's under heavy development, but there will be one in the future. For now, I'd recommend compiling the latest source code yourself.

**Comment by ThunderGemios10** [comment]
@forairan All right then.
